<a href="https://colab.research.google.com/github/dabster108/BuilingBlocksAi/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([5,4,6,5,2])

array([5, 4, 6, 5, 2])

In [ ]:
a = np.array([5,4,6,5,2])
a

array([5, 4, 6, 5, 2])

In [ ]:
a[2] = 10
a

array([ 5,  4, 10,  5,  2])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi dimensional Array

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
n =np.array([
    [1,3,4],
    [15,53,4],
    [11,23,43],

])
n

array([[ 1,  3,  4],
       [15, 53,  4],
       [11, 23, 43]])

In [ ]:
n[0,1] = 20
n

array([[ 1, 20,  4],
       [15, 53,  4],
       [11, 23, 43]])

In [ ]:
n[2] = [1,1,1]
n

array([[ 1, 20,  4],
       [15, 53,  4],
       [ 1,  1,  1]])

In [ ]:
n[:,2] = [0,1,2]
n

array([[ 1, 20,  0],
       [15, 53,  1],
       [ 1,  1,  2]])

In [ ]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.rand(3)

array([0.62113383, 0.52914209, 0.13457995])

In [ ]:
np.random.seed(2)
np.random.randn(5,2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

Element wise Operation

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = (10+ (a*2))
b

array([10, 12, 14, 16, 18])

Comparison Operator

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a >=2

array([False, False,  True,  True,  True])

In [ ]:
b

array([10, 12, 14, 16, 18])

In [ ]:
a >b

array([False, False, False, False, False])

Summarizing the Data

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a.std()

1.4142135623730951

In [ ]:
a.min()

0

In [ ]:
a.max();
a

array([0, 1, 2, 3, 4])

In [ ]:
a.sum();

In [ ]:
import numpy as np
import sys

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a[0]

1

In [ ]:
a[0:]


array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2] #skip

array([1, 3])

In [ ]:
import numpy as np
n =np.array([
    [1,3,4],
    [15,53,4],
    [11,23,43],

])
n.shape
n.size



9

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


Broadcasting and Vectorized Operations


In [4]:
import numpy as np
a = np.arange(4)
print(a)

[0 1 2 3]


In [5]:
a+10

array([10, 11, 12, 13])

In [12]:
a * 10


array([ 0, 10, 20, 30])

In [14]:
a += 100
a


array([200, 201, 202, 203])

In [11]:
 l = [ 0 , 1 , 2 ,3 ]
 [i * 10 for i in l]

[0, 10, 20, 30]

In [17]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [18]:
b = np.array([10,10,10,10])
b

array([10, 10, 10, 10])

In [19]:
a +b


array([10, 11, 12, 13])

In [20]:
a * b


array([ 0, 10, 20, 30])

In [21]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

Boolean Arrays

In [23]:
import numpy as np
a  = np.arange(4)

In [24]:
a >=2

array([False, False,  True,  True])

In [29]:
a.mean() > 3

np.False_

In [30]:
a[a>=2]

array([2, 3])

In [31]:
a[a >= a.mean()]

array([2, 3])

In [33]:
import numpy as np
A = np.random.randint(100, size=(3, 3))  # Generates a 3x3 matrix with random integers from 0 to 99
print(A)

[[43 35 13]
 [89 10 62]
 [62 89  8]]


In [34]:
A > 30

array([[ True,  True, False],
       [ True, False,  True],
       [ True,  True, False]])

In [36]:
A[A > 33]


array([43, 35, 89, 62, 62, 89])

Linear Algebra