<a href="https://colab.research.google.com/github/dabster108/BuilingBlocksAi/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np



In [10]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [17]:
np.array([5,4,6,5,2])

array([5, 4, 6, 5, 2])

In [19]:
a = np.array([5,4,6,5,2])
a

array([5, 4, 6, 5, 2])

In [22]:
a[2] = 10
a

array([ 5,  4, 10,  5,  2])

In [24]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi dimensional Array

In [28]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [31]:
np.zeros((2,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
n =np.array([
    [1,3,4],
    [15,53,4],
    [11,23,43],

])
n

array([[ 1,  3,  4],
       [15, 53,  4],
       [11, 23, 43]])

In [40]:
n[0,1] = 20
n

array([[ 1, 20,  4],
       [15, 53,  4],
       [11, 23, 43]])

In [43]:
n[2] = [1,1,1]
n

array([[ 1, 20,  4],
       [15, 53,  4],
       [ 1,  1,  1]])

In [46]:
n[:,2] = [0,1,2]
n

array([[ 1, 20,  0],
       [15, 53,  1],
       [ 1,  1,  2]])

In [47]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [48]:
np.random.rand(3)

array([0.62113383, 0.52914209, 0.13457995])

In [49]:
np.random.seed(2)
np.random.randn(5,2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

Element wise Operation

In [51]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [52]:
b = (10+ (a*2))
b

array([10, 12, 14, 16, 18])

Comparison Operator

In [53]:
a

array([0, 1, 2, 3, 4])

In [54]:
a >=2

array([False, False,  True,  True,  True])

In [55]:
b

array([10, 12, 14, 16, 18])

In [56]:
a >b

array([False, False, False, False, False])

Summarizing the Data

In [57]:
a

array([0, 1, 2, 3, 4])

In [58]:
a.std()

1.4142135623730951

In [59]:
a.min()

0

In [65]:
a.max();
a

array([0, 1, 2, 3, 4])

In [63]:
a.sum();